


all2:
	docker build --platform linux/arm64  --build-arg TARGETARCH=arm64 --no-cache  --progress=plain -t tmp:v0.1 .
# docker build --build-arg TARGETARCH=arm64 --no-cache  --progress=plain -t tmp:v0.1 .

all:
	docker build --no-cache --progress=plain -t tmp:v0.1 .

